apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::346678417543:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::346678417543:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4Y1SYNR44XCS
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-25T15:48:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1274"
  uid: 5930912a-1e29-4ee7-a1f8-7450b301c8ed
